module.exports.sampleData = {
  createdAt: "2021-07-21T20:42:43.004Z",
  currentState: "4",
  educationalLevel: "WASSCE",
  educationInfo: {
    bece: {
      grades: [
        { name: "English Language", grade: "1" },
        { name: "Integrated Science", grade: "1" },
        { name: "Mathematics", grade: "1" },
        { name: "Basic Design & Technology", grade: "1" },
        { name: "Religous & Moral Education", grade: "1" },
        { name: "Social Studies", grade: "1" },
      ],
      indexNumber: "10660934434",
      nameOfSchool: "Learning Field International School",
    },
    wassce: {
      schools: [
        {
          courseOffered: "General Science",
          grade1: "B2",
          grade2: "A1",
          grade3: "A1",
          grade4: "A1",
          grade5: "B2",
          grade6: "B2",
          indexNumber: "1088877865",
          nameOfSchool: "Action Chapel's School",
          subject1: "English Language",
          subject2: "Integrated Science",
          subject3: "Social Studies",
          subject4: "Biology",
          subject5: "Elective Mathematics",
          subject6: "Chemistry",
          wassceResultNumber: "1000000000",
        },
        {
          courseOffered: "General Science",
          grade1: "A1",
          grade2: "A1",
          grade3: "A1",
          grade4: "A1",
          grade5: "A1",
          grade6: "A1",
          indexNumber: "109933434",
          nameOfSchool: "Presbyterian Boys' Secondary School",
          subject1: "English Language",
          subject2: "Social Studies",
          subject3: "Core Mathematics",
          subject4: "Biology",
          subject5: "Integrated Science",
          subject6: "Elective Mathematics",
          wassceResultNumber: "100999234",
        },
      ],
    },
    tetiary: {
      tetiaryClass: "Second Class Upper",
      tetiaryIndexNumber: "10665476",
      tetiaryInstitution: "University Of Ghana, Legon",
      tetiaryProgramme: "Computer Science",
    },
    others: {
      course: "Cisco Certified Network Associate",
      durationNumber: "6",
      durationType: "Months",
      otherInstitution: "Kofi Anan IT Center",
      referenceNumber: "0000023434",
    },
    nvti: {
      nvtiProgramme: "",
      nameOfNVTIInstution: "",
      nvtiCertificateNumber: "",
      nvtiClass: "",
    },
    hnd: {
      hndProgramme: "",
      nameOfHNDInstution: "",
      hndCertificateNumber: "",
      hndClass: "",
    },
    nss: {
      course: "Cisco Certified Network Associate",
      durationNumber: "6",
      durationType: "Months",
      otherInstitution: "Kofi Anan IT Center",
      referenceNumber: "0000023434",
    },
  },
  familyInfo: {
    father: {
      alive: true,
      name: "Rev. Fiifi Foh Arkhurst",
      phone: "0208090946",
    },
    mother: {
      alive: true,
      name: "Mr. Jennifer Foh Arkhurst",
      phone: "0243311464",
    },
    fullNameOfNextofKin: "Prince Foh Arkhurst",
    phoneNumberOfNextofKin: "0507715063",
  },
  personalInfo: {
    applicantsHomeTown: "Kibi",
    birthCerticateNumber: "00000000234323",
    dob: "1999-07-09",
    emailAddress: "fiifi.arkhurst@afrilogicsolutions.com",
    firstName: "Jnr",
    gender: "Male",
    ghanaPost: "GE-0210-2342",
    height: "1.7",
    homeDistrict: "East Akim Municipal",
    homeRegion: "Central Region",
    maritalStatus: "Married",
    otherNames: "Fiifi",
    phoneNumber: "0242379278",
    placeOfBirth: "Breman Asikuma",
    residentialAddress: "Aburi",
    surname: "Foh Arkhurst",
    weight: "52",
  },
  pictureUrl:
    "https://projectxgh.blob.core.windows.net/passportcontainer/965ebd1c-896d-4601-a7c4-6bf0e30d7626Screenshot 2021-02-17 at 5.01.09 PM.png",
  referenceNumber: "GIS-328552-21",
  special: false,
  specialCode: "",
  status: { code: 10, name: "NEW", description: "Application in progress" },
  token: "OBLWYS7H85",
  type: "OFFICERS",
  updatedAt: "2021-07-21T21:05:06.374Z",
};
